### ISSUE TITLE
There is a modified version 

### ISSUE THREAD

**Issue by emdee-is** [NucleaPeon/gentooimgr#1]
There is a modified version at https://git.plastiras.org/emdee/libvirt_cloud/src/branch/main/src/ansible_gentooimgr
where we've modified the code a little to do use Python logging and maybe fixed a bug or two. We can still use it for the build stage, but we think the install stage is better done using ansible, hence the libvirt_cloud playbook; you don't check return values in your install steps, and I'm confused on the precedence of the config json file.
I think you should merge args into the configjson object and have the code work only on the merged object: the precedence shouldn't be down in the code.

The code is a WIP so look to see if the repo is active. It's being supported as an ansible module using library/ansible_gentooimgr.py which is a work in progress; the idea is to use it for the build and status test? actions, but handle the install tasks using ansible.

Instead of using cloud-init, our approach is to build a base image with qemu-guest-agent installed which means you don't need cloud-init. That means you don't need 384 crates of opaque googled code. Apart from making the base smaller, it makes it auditable, I can't imaging why the libvirt base images on the Internet don't include qemu-guest-agent.........

Take any of the code you want back into your repo: I think the changes are all logging and bulletproofing. If you use ansible you can maintain the library file. If you don't maybe it a good time to look at it, because writing the install in Python will be painfully limiting, and it may take you a while to write tests.py.

Please wrap the code after if __name__ == "__main__" in __main__.py into a function that returns an int, 0 on success so it's callable from an import.

**Comment by NucleaPeon** [comment]
Hi there, thanks for the contribution.

> cloud-init vs qemu-guest-agent

I agree that cloud-image bringing in rust is a disappointment. I checked the dependencies just in case, but it's tied to cloud-init. It makes sense to have a configuration for plain qemu, so I'll create a config that only builds a minimal qemu image without cloud-init.

I haven't yet looked at the repository, but logging code would definitely be useful and I wanted to implement that. 

> ansible

I'm hesitant to add in additional technologies into this project. I want it to be as straight forward for less technical users and have as few dependencies as possible. I'm not against using ansible or terraform to build the images and it would make testing easier, but I'm not sure I have the time to invest in integrating what could be a substantial change in how things are currently done right now. Honestly I just wanted a Gentoo image template to use in Proxmox and later, a powerpc Gentoo image.

That said, it does make sense to support ansible and terraform for this project's longevity, but it will be a longer term objective and not something I do to resolve this issue. I'll create a ticket to refer to this.

> return codes

I will also add this in.

> Config precedence

First we load a 'default' configuration, which is the top-level/cli specified configuration or the base.json config if nothing is specified; The 'default' can be a built in ``--config-_____`` option or one on the filesystem you wrote. Everything in this default config is applied via an update() call after everything else has been resolved and merged together; merging your default configuration is the last step that occurs BUT will specifically override any package keys you have set. 

*For example, if you specify using a binary distribution kernel, but the base.json config has a source-based kernel, you don't want sys-kernel/gentoo-kernel-bin and sys-kernel/gentoo-kernel (or gentoo-sources in base.json for example) being merged together because that will inflate the image and include many files that sit unused. Setting the packages['kernel'] = [...] will override the base.json's packages['kernel'] list.*

For inheritance:

If the default config has an inherit key set, we call inherit_config() and that will recursively call update() starting from the very base file (with no inherit value).

If you wanted to build upon cloud.json, you would run something like:

```sh
python -m gentooimgr install --config /tmp/my.json
```

That would result in a config being built in this order:
```
json = base.json  # inherited by cloud.json
json.update(cloud.json)  # inherited by my.json
# any number of inherits can occur between cli and your base config.
# inherit is a path; internally, it's a relative one based in the configs/ dir unless you specify an absolute path.
json.update(my.json) # Top level configuration specified on cli
```

**Comment by emdee-is** [comment]
Take a look at my code and pull back the Python logging changes at the very least - there may also be a bug or two I squashed.

Rust inflitration is a real problem for me - all gentoos Rust crates are no longer available over Tor, And cloud-init is unnecessary on any libvirt system which has qemu-guest-agent installed. GA is a valid connection for ansible, so you don't need cloud-init and you can do everything from the bootstrapped box from ansible, Look in my lib/ directory for a slightly improved libvirt_qemu.py.

Look at your install.py and compare to what one can cover with an ansible role, and I think you'll see that doing the install in Python is too limited and error prone.
